/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Am4core: typeof import('./src/components/am4core.vue')['default']
    ComparePool: typeof import('./src/components/ComparePool.vue')['default']
    CulturalAlignment: typeof import('./src/components/Comparison/CulturalAlignment.vue')['default']
    DimensionMeasurementTabs: typeof import('./src/components/DimensionMeasurementTabs.vue')['default']
    Echart: typeof import('./src/components/Comparison/echart.vue')['default']
    EchartComponent: typeof import('./src/components/Analysis/EchartComponent.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HomepageSwiper: typeof import('./src/components/homepageSwiper.vue')['default']
    Intro: typeof import('./src/components/Home/intro.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    ModelListCheckbox: typeof import('./src/components/ModelListCheckbox.vue')['default']
    ModelListRadio: typeof import('./src/components/ModelListRadio.vue')['default']
    Modules: typeof import('./src/components/Home/modules.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    NavBarNew: typeof import('./src/components/navBarNew.vue')['default']
    Posts: typeof import('./src/components/Home/posts.vue')['default']
    PostsOld: typeof import('./src/components/Home/posts-old.vue')['default']
    RadarChart: typeof import('./src/components/radar-chart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveImage: typeof import('./src/components/saveImage.vue')['default']
    ScoreIntro: typeof import('./src/components/scoreIntro.vue')['default']
    SelectBox: typeof import('./src/components/selectBox.vue')['default']
    SelectedPoints: typeof import('./src/components/selectedPoints.vue')['default']
    SelectedPointsOld: typeof import('./src/components/selectedPointsOld.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
    Swiper: typeof import('./src/components/swiper.vue')['default']
    Table: typeof import('./src/components/Comparison/Table.vue')['default']
    TestValuesResults: typeof import('./src/components/TestValues/TestValuesResults.vue')['default']
    ValueSpace: typeof import('./src/components/Comparison/ValueSpace.vue')['default']
    Visualization: typeof import('./src/components/Comparison/Visualization.vue')['default']
    Visualization_new: typeof import('./src/components/Comparison/Visualization_new.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
