#-------------------------------
# General Site Settings
title: Value Compass
logo: logo.png # You can add own logo.
description: Aligning AI with Basic Human Values


#-------------------------------
# Project Settings
project:
  name: Aligning AI with Basic Human Values
  description: To push the frontier of AI towards a human-machine symbiotic future, we propose the interdisciplinary value compass project, aiming to achieve LLM alignment based on the basic values from humanity and social science. Three parts are mainly explored:1) efficient and adaptive alignment algorithms; 2) reliable value evaluation systems; and 3) interdisciplinary studies on values and machine ethics. Hoping to create a new generation of AI systems that compatible with human values of various cultural contexts.
  image: home_cover.png
  email: valuecompass@microsoft.com
  github: https://github.com/microsoft/ValueCompass.git

#-------------------------------
# PapersPage Settings
PagesPage:
  name: Publications Hub
  description: Explore our comprehensive collection of published papers covering various topics within the Value Compass project. Stay informed and delve into the latest research insights and findings from our team.
  image: pages_cover.png

TalksPage:
  name: Welcome to our Insights & Events page!
  description: <p>Explore a collection of interviews, conference highlights, and event videos to stay informed and inspired by engaging discussions with experts.</p><p>Stay ahead of the curve with our insights that provide a deeper understanding of the latest trends and developments in the field of AI values and ethics.</p>

ResourcesPage:
  name: "Research Resources: Up-to-date Survey of LLM Value Alignment"
  description: Explore key resources about large language models (LLMs) value alignment, including papers, benchmarks and open-sourced projects. We aim to engage more researchers and facilitate an easy entry into this critical research area.
  image: resource_cover.png


#-------------------------------
# Contact links
xiaoyuan: xiaoyuanyi@microsoft.com
jingyao: jingyao@microsoft.com
github: https://github.com/ValueCompass/ValueCompass.github.io

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
