#-------------------------------
# General Site Settings
title: Value Compass
logo: logo.png # You can add own logo.
description: Aligning AI with Basic Human Values


#-------------------------------
# Project Settings
project:
  name: Aligning AI with Basic Human Values
  description: To push the frontier of AI towards a human-machine symbiotic future, we propose the interdisciplinary value compass project, aiming to achieve LLM alignment based on the basic values from humanity and social science. Three parts are mainly explored:1) efficient and adaptive alignment algorithms; 2) reliable value evaluation systems; and 3) interdisciplinary studies on values and machine ethics. Hoping to create a new generation of AI systems that compatible with human values of various cultural contexts.
  image: home_cover.png
  email: valuecompass@microsoft.com
  github: https://github.com/microsoft/ValueCompass.git

#-------------------------------
# PapersPage Settings
PagesPage: 
  name: Publications Hub 
  description: This page houses a collection of published papers covering various topics within the Value Compass project. It provides a detailed overview of our research progress and findings, focusing on interdisciplinary analysis, benchmarks, value evaluation and alignment techniques.
  image: pages_cover.png

TalksPage:
  name: Events & Insights
  description: This page offers a repository of interviews, conference presentations, and workshop discussions. It delivers our understanding and insights about the latest trends and developments in the fields of AI ethics and value alignment.

ResourcesPage:
  name: "Research Resources: Up-to-date Survey of LLM Value Alignment"
  description: This page consolidates key resources about large language models (LLMs) value alignment, including research papers, benchmarks and open-sourced projects. It aims to engage more researchers and facilitate an easy entry into this critical research area.
  image: resource_cover.png


#-------------------------------
# Contact links
xiaoyuan: xiaoyuanyi@microsoft.com
jingyao: jingyao@microsoft.com
github: https://github.com/ValueCompass/ValueCompass.github.io

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
